# Esse Workflow é responsável por gerar releases da biblioteca.

name: Create release for anpr

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to source branch
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies and prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout
          python -m pip install -r requirements.txt
          python -m pip install -e .

      - name: Run tests with pytest
        run: pytest --timeout=60

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to dev
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip install wheel

      - name: Build package
        run: |
          python -m build .

      - name: Extract version tag
        id: extract-tag
        run: |
          echo "tag=v$(grep 'version =' pyproject.toml | tr -d version=\" | tr -d '[:blank:]')" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract-tag.outputs.tag }}
          target_commitish: main
          name: Versão ${{ steps.extract-tag.outputs.tag }}
          prerelease: false
          draft: false
          files: ./dist/*
          body: "Versão estável da biblioteca anpr."