# Esse Workflow é responsável pela execução dos testes unitários da biblioteca.

name: Tests with pytest

on:
  pull_request:
    paths:
      - 'anpr/**'
      - 'tests/**'
      - '.github/**'

jobs:
  test:
    permissions:
      contents: 'write'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout to source branch
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies and prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout
          python -m pip install -r requirements.txt
          python -m pip install -e .
  
      - name: Run tests with pytest
        run: pytest --timeout=60